{
 "title": "MariaDB metrics",
 "time": { "from": "2024-10-26T05:35:24.925Z", "to": "2024-10-28T05:35:24.925Z" },
 "panels": [
  {
   "title": "Total number of requests",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mysql_global_status_questions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Select",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"select\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of current connections",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"insert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"update\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"delete\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}