{
 "title": "OS metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Use CPU in %",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu, instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Use RAM in %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Use FS in %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device!=\"\"} - node_filesystem_free_bytes{device!=\"\"}) / node_filesystem_size_bytes{device!=\"\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "incoming traffic",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "News", "type": "news", "gridPos": { "h": 28, "w": 24, "x": 0, "y": 33 } }
 ]
}